# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djorm_pgfulltext.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Категории статей',
                'db_table': 'category',
                'verbose_name': 'Категория статей',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Статья')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, default='post/default.jpg', upload_to='post')),
                ('pageviews', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество просмотров')),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='post.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
                'ordering': ['-created'],
                'verbose_name': 'Статья',
            },
            managers=[
                ('search_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RuTag',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='RuTaggedItem',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('taggit.taggeditem',),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='post.RuTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
