# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 11:35
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Наименование')),
                ('descriptions', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name_plural': 'Дополнительная информация',
                'db_table': 'additional_information',
                'verbose_name': 'Дополнительная информация',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('body', models.TextField(verbose_name='Описание услуги')),
                ('new_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Новая цена')),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Старая цена')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'db_table': 'service',
                'verbose_name': 'Услуга',
            },
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, default='services/default.jpg', upload_to='services', verbose_name='Изображение')),
                ('descriptions', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Категории услуг',
                'db_table': 'type_of_service',
                'verbose_name': 'Категория услуг',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='type_of_service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='services.TypeOfService', verbose_name='Вид услуг'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Услуга'),
        ),
    ]
