"""
Django settings for BeautySpot project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oit+%hdfpw66@_c%wrma@jvf@yx87v_2xf3e_3+#j_qi0d%_08'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['127.0.0.1:8000']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'sorl.thumbnail',
    'model_utils',
    'taggit',
    'braces',
    'disqus',
    'djorm_pgfulltext',
    'psycopg2',
    'ckeditor',
    'ckeditor_uploader',
    'meta',
    'robots',
    'BS',
    'BS.templatetags',
    'BS.post',
    'BS.services',
    'BS.gallery',
    'BS.social',
)


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'BeautySpot.urls'

#TEMPLATE_DEBUG = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BeautySpot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Sergey1592',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'zsergey_zserge77',
#         'USER': 'zsergey_zserge77',
#         'PASSWORD': 'eBmCnTl8jd8',
#         'HOST': 'postgresql0.locum.ru',
#         'PORT': '5432',
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

SITE_ID = 1

THUMBNAIL_DEBUG = True


STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#DISQUS_API_KEY = 'FOOBARFOOBARFOOBARFOOBARFOOBARF'
DISQUS_WEBSITE_SHORTNAME = 'beautyspot-sml'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}


CKEDITOR_JQUERY_URL = 'static/js/jquery.js'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = True
CKEDITOR_BROWSE_SHOW_DIRS = True

META_SITE_PROTOCOL = 'http'
META_SITE_DOMAIN = 'smolnails.ru'
META_SITE_NAME = 'SmolNails'
META_USE_TITLE_TAG = True
META_INCLUDE_KEYWORDS = ['ногти','маникюр','фото','гель лак','салон красоты','смоленск','новинки','френч']


ROBOTS_USE_SITEMAP = False
ROBOTS_SITEMAP_URLS = [
    'http://smolnails.ru/sitemap.xml',
]

THUMBNAIL_ENGINE = 'watermarker.sorl_engine.WatermarkEngine'
# WATERMARK_MIN_SIZE = 50
# WATERMARK_FORCE = 'Published on blog.djangofan.ru'
WATERMARK_OPTIONS = {
   'font_scale': 0.1,
   'font_path':os.path.join('static/fonts/', 'PFDavinciScriptPro-Reg.ttf'),
   'color': (255, 255, 255),
}